/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgPenyakit.java
 *
 * Created on May 23, 2010, 12:57:16 AM
 */

package keuangan;

import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author dosen
 */
public final class DlgTemplateLaboratorium2 extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    
    private HashMap<String, String> mapKet = new HashMap<>();
    /** Creates new form DlgPenyakit
     * @param parent
     * @param modal */
    public DlgTemplateLaboratorium2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10,2);
        setSize(656,250);
        tabMode = new DefaultTableModel(null, new String[]
        {
            "ID Det Template","ID Template", "Pemeriksaan", "Satuan", "Nilai Rujukan LD", "Nilai Rujukan LA",
            "Nilai Rujukan PD", "Nilai Rujukan PA"
        })
        {
             @Override public boolean isCellEditable(int rowIndex, int colIndex){
                boolean a = true;
                if (colIndex==8) {
                    a=false;
                }
                return a;
             }
             Class[] types = new Class[] {
                java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,
                java.lang.Object.class,java.lang.Object.class,java.lang.Double.class,java.lang.Double.class
//                java.lang.Double.class,java.lang.Double.class,java.lang.Double.class,java.lang.Double.class, 
//                java.lang.Double.class,java.lang.Double.class,java.lang.Object.class,java.lang.Object.class
             };

        };
        
        tblTemplate.setModel(tabMode);
        tblTemplate.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tblTemplate.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int i = 0; i < 8; i++)
        {
            TableColumn column = tblTemplate.getColumnModel().getColumn(i);
            if (i == 0)
            {
                column.setPreferredWidth(90);
            }
            else if (i == 1)
            {
                column.setPreferredWidth(110);
            }
            else if (i == 2)
            {
                column.setPreferredWidth(240);
            }
            else if (i == 3)
            {
                column.setPreferredWidth(112);
            }
            else if (i == 4)
            {
                column.setPreferredWidth(113);
            }
            else if (i == 5)
            {
                column.setPreferredWidth(114);
            }
            else if (i == 6)
            {
                column.setPreferredWidth(115);
            }
            else if (i == 7)
            {
                column.setPreferredWidth(115);
            }            
        }
        
        tblTemplate.setDefaultRenderer(Object.class, new WarnaTable());
  
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tblTemplate = new widget.Table();
        panelisi3 = new widget.panelisi();
        label9 = new widget.Label();
        KdPeriksa = new widget.TextBox();
        NmPeriksa = new widget.TextBox();
        BtnTambah = new widget.Button();
        BtnSimpan = new widget.Button();
        BtnHapus = new widget.Button();
        jLabel10 = new widget.Label();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Detail Template Pemeriksaan Laboratorium ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 70, 40))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tblTemplate.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tblTemplate.setName("tblTemplate"); // NOI18N
        tblTemplate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTemplateMouseClicked(evt);
            }
        });
        tblTemplate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblTemplateKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tblTemplate);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelisi3.setName("panelisi3"); // NOI18N
        panelisi3.setPreferredSize(new java.awt.Dimension(100, 43));
        panelisi3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 9));

        label9.setText("Pemeriksaan :");
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(82, 23));
        panelisi3.add(label9);

        KdPeriksa.setName("KdPeriksa"); // NOI18N
        KdPeriksa.setPreferredSize(new java.awt.Dimension(100, 23));
        panelisi3.add(KdPeriksa);

        NmPeriksa.setName("NmPeriksa"); // NOI18N
        NmPeriksa.setPreferredSize(new java.awt.Dimension(330, 23));
        panelisi3.add(NmPeriksa);

        BtnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        BtnTambah.setMnemonic('3');
        BtnTambah.setToolTipText("Alt+3");
        BtnTambah.setName("BtnTambah"); // NOI18N
        BtnTambah.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });
        panelisi3.add(BtnTambah);

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        panelisi3.add(BtnSimpan);

        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('H');
        BtnHapus.setToolTipText("Alt+H");
        BtnHapus.setName("BtnHapus"); // NOI18N
        BtnHapus.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        panelisi3.add(BtnHapus);

        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(70, 23));
        panelisi3.add(jLabel10);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('4');
        BtnKeluar.setToolTipText("Alt+4");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelisi3.add(BtnKeluar);

        internalFrame1.add(panelisi3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        if(KdPeriksa.getText().equals("")||NmPeriksa.getText().equals("")){
            Valid.textKosong(KdPeriksa,"Pemeriksaan");
        }else{
            if(tblTemplate.getSelectedRow()>-1){                
                tabMode.insertRow(tblTemplate.getSelectedRow(),new Object[]{"","","","","","",0,0,0,0,0,0,0,0,""});
            }else{
                tabMode.addRow(new Object[]{"","","","","","",0,0,0,0,0,0,0,0,"",""});
                tblTemplate.requestFocus();
            }
            urut();
        }
    }//GEN-LAST:event_BtnTambahActionPerformed

private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
    if(KdPeriksa.getText().equals("")||NmPeriksa.getText().equals("")){
        Valid.textKosong(KdPeriksa,"Pemeriksaan");
    }else{
        int reply = JOptionPane.showConfirmDialog(rootPane,"Eeiiiiiits, udah bener belum data yang mau disimpan..??","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_OPTION) {
             int row=tblTemplate.getRowCount();
             if(row>-1){
                 for(int i=0;i<row;i++){  
                     //System.out.println(tbKamar.getValueAt(i,0).toString());
                    if(tblTemplate.getValueAt(i,14).toString().equals("")){
                         Sequel.menyimpan("template_laboratorium","?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?","Id Hasil Periksa",17,new String[]{
                               KdPeriksa.getText(),"0",tblTemplate.getValueAt(i,0).toString(),tblTemplate.getValueAt(i,1).toString(),
                               tblTemplate.getValueAt(i,2).toString(),tblTemplate.getValueAt(i,3).toString(),tblTemplate.getValueAt(i,4).toString(),
                               tblTemplate.getValueAt(i,5).toString(),tblTemplate.getValueAt(i,6).toString(),tblTemplate.getValueAt(i,7).toString(),
                               tblTemplate.getValueAt(i,8).toString(),tblTemplate.getValueAt(i,9).toString(),tblTemplate.getValueAt(i,10).toString(),
                               tblTemplate.getValueAt(i,11).toString(),tblTemplate.getValueAt(i,12).toString(),tblTemplate.getValueAt(i,13).toString(),
                               tblTemplate.getValueAt(i,15).toString()       
                         });
                    }else if(!tblTemplate.getValueAt(i,14).toString().equals("")){
                         Sequel.mengedit("template_laboratorium","id_template=?","Pemeriksaan=?,satuan=?,nilai_rujukan_ld=?,nilai_rujukan_la=?,"+
                               "nilai_rujukan_pd=?,nilai_rujukan_pa=?,bagian_rs=?,bhp=?,bagian_perujuk=?,bagian_dokter=?,bagian_laborat=?,kso=?,menejemen=?,biaya_item=?,urut=?",16,new String[]{
                               tblTemplate.getValueAt(i,0).toString(),tblTemplate.getValueAt(i,1).toString(),tblTemplate.getValueAt(i,2).toString(),tblTemplate.getValueAt(i,3).toString(),
                               tblTemplate.getValueAt(i,4).toString(),tblTemplate.getValueAt(i,5).toString(),tblTemplate.getValueAt(i,6).toString(),tblTemplate.getValueAt(i,7).toString(),
                               tblTemplate.getValueAt(i,8).toString(),tblTemplate.getValueAt(i,9).toString(),tblTemplate.getValueAt(i,10).toString(),tblTemplate.getValueAt(i,11).toString(),
                               tblTemplate.getValueAt(i,12).toString(),tblTemplate.getValueAt(i,13).toString(),tblTemplate.getValueAt(i,15).toString(),tblTemplate.getValueAt(i,14).toString()
                         } );   
                    }
                 }
                 tampil();
             }             
        }
    }        
}//GEN-LAST:event_BtnSimpanActionPerformed

private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
   try{
       Sequel.meghapus("template_laboratorium","id_template",tblTemplate.getValueAt(tblTemplate.getSelectedRow(),14).toString());
       tabMode.removeRow(tblTemplate.getSelectedRow());
       urut();
   }catch(Exception ex){
       JOptionPane.showMessageDialog(null,"Pilih dulu data yang mau dihapus..!!");
   }
}//GEN-LAST:event_BtnHapusActionPerformed

    private void tblTemplateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblTemplateKeyPressed
        if(tblTemplate.getRowCount()!=0){
            if((evt.getKeyCode()==KeyEvent.VK_ENTER)||(evt.getKeyCode()==KeyEvent.VK_UP)||(evt.getKeyCode()==KeyEvent.VK_DOWN)){
                try {
                    getData();
                } catch (java.lang.NullPointerException e) {
                }
            }            
        }
    }//GEN-LAST:event_tblTemplateKeyPressed

    private void tblTemplateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTemplateMouseClicked
        if(tblTemplate.getRowCount()!=0){
            try {
                getData();
            } catch (java.lang.NullPointerException e) {
            } 
        }
    }//GEN-LAST:event_tblTemplateMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgTemplateLaboratorium2 dialog = new DlgTemplateLaboratorium2(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnHapus;
    private widget.Button BtnKeluar;
    private widget.Button BtnSimpan;
    private widget.Button BtnTambah;
    public widget.TextBox KdPeriksa;
    public widget.TextBox NmPeriksa;
    private widget.ScrollPane Scroll;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel10;
    private widget.Label label9;
    private widget.panelisi panelisi3;
    private widget.Table tblTemplate;
    // End of variables declaration//GEN-END:variables

    public void tampil() {
        
        
        Valid.tabelKosong(tabMode);
        try{            
            ps=koneksi.prepareStatement("SELECT id_det_template, id_template, pemeriksaan, satuan, nilai_rujukan_ld, nilai_rujukan_la, nilai_rujukan_pd, nilai_rujukan_pa " +
                            "FROM template_laboratorium_det WHERE id_template = ? ORDER BY id_det_template");
            try {
                ps.setString(1,KdPeriksa.getText());
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new Object[]
                    {
                        rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4),
                        rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)
                    });
                }
            //    urut();
            } catch (Exception e) {
                System.out.println(e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
    }
    private void getData() {
        int row=tblTemplate.getSelectedRow();
        if(row!= -1){
            if((!tblTemplate.getValueAt(row,6).toString().equals(""))
                    &&(!tblTemplate.getValueAt(row,7).toString().equals(""))
                    &&(!tblTemplate.getValueAt(row,8).toString().equals(""))
                    &&(!tblTemplate.getValueAt(row,9).toString().equals(""))
                    &&(!tblTemplate.getValueAt(row,10).toString().equals(""))
                    &&(!tblTemplate.getValueAt(row,11).toString().equals(""))
                    &&(!tblTemplate.getValueAt(row,12).toString().equals(""))){
               tblTemplate.setValueAt(Valid.SetAngka(tblTemplate.getValueAt(row,6).toString())+
                       Valid.SetAngka(tblTemplate.getValueAt(row,7).toString())+
                       Valid.SetAngka(tblTemplate.getValueAt(row,8).toString())+
                       Valid.SetAngka(tblTemplate.getValueAt(row,9).toString())+
                       Valid.SetAngka(tblTemplate.getValueAt(row,10).toString())+
                       Valid.SetAngka(tblTemplate.getValueAt(row,11).toString())+
                       Valid.SetAngka(tblTemplate.getValueAt(row,12).toString()), row,13); 
            }
        }
    } 
    
    public JTextField getTextField(){
        return KdPeriksa;
    }

    public JButton getButton(){
        return BtnKeluar;
    }
    
    public void urut(){
        if(tblTemplate.getRowCount()>-1){
            for(int i=0;i<tblTemplate.getRowCount();i++){  
                  tblTemplate.setValueAt(i, i,8);
            }
        }
    }
}
